/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 tableObject.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/tableObject.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Line01.geometry} material={nodes.Line01.material} />
      <mesh geometry={nodes.Cylinder01.geometry} material={nodes.Cylinder01.material} />
      <mesh geometry={nodes.Cylinder03.geometry} material={nodes.Cylinder03.material} />
    </group>
  )
}

useGLTF.preload('/tableObject.gltf')
